### ISSUE TITLE
Linting and tooltips broken in Sublime Text `Build 4107`

### ISSUE THREAD

**Issue by denis130** [buildersbrewery/sublime-lsl#8]
After updating or installing Sublime Text `Build 4107` and installing all the packages, linting doesn't work and after restarting Sublime Text tooltips are not displayed.

I have tried to do a clean install, removing everything related to previous versions, and it doesn't solve the issue.

### Environment

```yaml
Sublime Text:
  build: 4107
  channel: dev
    portable: false
  platform: windows x64

Packages:
    =BB= LSL:
        version: 6.0.0
        installed via Package Control: True
    Package Control: 3.4.1
    PackageDev: 3.2.16

Dependencies:
    SublimeLinter: 4.16.3
    markupsafe: 1.1.1
    mdpopups: 4.1.2
    pygments: 2.0.2
    python-jinja2: 2.10.1
    python-markdown: 3.1.1
    pyyaml: 5.1.1
    ruamel-yaml: 1.2.0
    sublime_lib: 1.4.0
```
